version: '2'

volumes:
  db:

networks:
  default:

services:
  app:
    build:
      context: ../
      dockerfile: minesweeper_docker/Dockerfile
    restart: unless-stopped
    networks:
      - default
    env_file:
      - app.env
