version: '2'

volumes:
  db:

networks:
  default:

services:
  app:
    build:
      context: ../
      dockerfile: minesweeper_docker/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - default
    env_file:
      - app.env

  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - default
    env_file:
      - db.env
